<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="4" passed="3">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="32165" started-at="2016-04-13T14:19:10Z" finished-at="2016-04-13T14:19:42Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="32165" started-at="2016-04-13T14:19:10Z" finished-at="2016-04-13T14:19:42Z">
      <class name="com.globant.training.rocio_bossio.tests.Tests">
        <test-method status="PASS" signature="before()[pri:0, instance:com.globant.training.rocio_bossio.tests.Tests@1e56eb2]" name="before" is-config="true" duration-ms="4009" started-at="2016-04-13T11:19:10Z" finished-at="2016-04-13T11:19:14Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- before -->
        <test-method status="PASS" signature="case1()[pri:0, instance:com.globant.training.rocio_bossio.tests.Tests@1e56eb2]" name="case1" duration-ms="35" started-at="2016-04-13T11:19:14Z" description="Verifing if title displayed is the expected one" finished-at="2016-04-13T11:19:14Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- case1 -->
        <test-method status="PASS" signature="before()[pri:0, instance:com.globant.training.rocio_bossio.tests.Tests@1e56eb2]" name="before" is-config="true" duration-ms="1776" started-at="2016-04-13T11:19:14Z" finished-at="2016-04-13T11:19:16Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- before -->
        <test-method status="PASS" signature="case2()[pri:0, instance:com.globant.training.rocio_bossio.tests.Tests@1e56eb2]" name="case2" duration-ms="3798" started-at="2016-04-13T11:19:16Z" description="Verifying if the query has results displayed" finished-at="2016-04-13T11:19:19Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- case2 -->
        <test-method status="PASS" signature="before()[pri:0, instance:com.globant.training.rocio_bossio.tests.Tests@1e56eb2]" name="before" is-config="true" duration-ms="1871" started-at="2016-04-13T11:19:19Z" finished-at="2016-04-13T11:19:21Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- before -->
        <test-method status="FAIL" signature="case3()[pri:0, instance:com.globant.training.rocio_bossio.tests.Tests@1e56eb2]" name="case3" duration-ms="4527" started-at="2016-04-13T11:19:21Z" description="Verifying if a post date is the expected one" finished-at="2016-04-13T11:19:26Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Title is not displayed as expected expected [October 10, 2013] but found [null]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Title is not displayed as expected expected [October 10, 2013] but found [null]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:130)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:190)
	at com.globant.training.rocio_bossio.tests.Tests.case3(Tests.java:89)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- case3 -->
        <test-method status="PASS" signature="before()[pri:0, instance:com.globant.training.rocio_bossio.tests.Tests@1e56eb2]" name="before" is-config="true" duration-ms="2119" started-at="2016-04-13T11:19:26Z" finished-at="2016-04-13T11:19:28Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- before -->
        <test-method status="PASS" signature="case4()[pri:0, instance:com.globant.training.rocio_bossio.tests.Tests@1e56eb2]" name="case4" duration-ms="13813" started-at="2016-04-13T11:19:28Z" description="Send form and verify if it was properly sent" finished-at="2016-04-13T11:19:42Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- case4 -->
      </class> <!-- com.globant.training.rocio_bossio.tests.Tests -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
